apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  labels:
    app: multi-deploy
    app.kubernetes.io/name: multi-deploy
  name: multi-deploy
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: multi-deploy
