apiVersion: v1
kind: Service
metadata:
  labels:
    app: multi-deploy
    app.kubernetes.io/name: multi-deploy
  name: multi-deploy
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: multi-deploy
  type: NodePort
