apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  labels:
    app: multi-deploy
    app.kubernetes.io/name: multi-deploy
  name: multi-deploy
spec:
  host: multi-deploy
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN # New load balancer LEAST_REQUEST is default since 1.14.0
  exportTo:
    - "."
